name: 'fashion_mnist'
img_resolution: 28
in_channels: 1
out_channels: 1
label_dim: 10

batch_size: 128 # batch per gpu
num_workers: 16
data_dir: '.'
sample_shape: [256, 1, 28, 28]
plot_type: 'grid'
fid_sample_shape : [500, 1, 28, 28]
n_dataset_samples: 50000
