defaults:
  - dataset: cifar10
  - model: vcfm
  - network: edm

training:
  log_every: 100
  eval_every: 1000
  sample_every: 1000
  sample_steps: 50
  grad_clip: null
  output_dir: runs
  seed: 42

callbacks:
  generate: true
  fid: true
